minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyExclude:
  - eslint-import-resolver-typescript@3.10.1
  - reselect@5.1.1
  - semver@6.3.1

allowBuilds:
  '@tailwindcss/oxide': true
  sharp: true
  unrs-resolver: true
  "@heroui-pro/react": true
  "@zowe/secrets-for-zowe-sdk": true
  cos-js-sdk-v5: true
confirmModulesPurge: false
